# Generated by Django 4.2 on 2023-04-09 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SignUpPage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='profile_pic',
            field=models.ImageField(default='default_profile_pic.jpg', upload_to='profile_pics'),
        ),
    ]
