# Generated by Django 4.2 on 2023-04-09 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SignUpPage', '0002_index_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='index',
            name='profile_pic',
        ),
    ]
