# Generated by Django 4.2 on 2023-04-09 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SignUpPage', '0003_remove_index_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_pics/'),
        ),
    ]
