# Generated by Django 4.2 on 2023-04-09 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SignUpPage', '0007_remove_index_bio_remove_index_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='address',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='index',
            name='pincode',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='index',
            name='state',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
